# Generated by Django 4.2.7 on 2023-11-29 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date(2023, 11, 29), verbose_name='Премьера в мире'),
        ),
    ]
